export interface IGranulometria{
  tamices:{
  inches2:number;
  inches1:number;
  inches34:number;
  inches12:number;
  inches38:number;
  inchesN4:number;
  inchesN10:number;
  inchesN40:number;
  inchesN200:number;
  inchesP200:number;
  }
  data?:{
  total:number;
  retenido:number[]
  acum:number[]
  pasa:number
  grava:number
  arena:number
  finos:number
  sucsData:string
  observation:string
  }
}
export interface ISucsData{
  sucsData:string
  id:string
  sondeo:number
  layer:number
}
